### ISSUE TITLE
All entrypoint values appear to be overwritten with service for login/reg complete auth server events

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/fxa-shared#46]
I believe this is due to a change made in https://github.com/mozilla/fxa-shared/pull/40 

As I understand it, this should only be filling entrypoint with oauth client_id for null values, but it seems to be overwriting all of them:

https://analytics.amplitude.com/mozilla-corp/chart/wpnch2s

**Comment by irrationalagent** [comment]
CC @davismtl @shane-tomlinson @philbooth

**Comment by philbooth** [comment]
Ah yeah, I think I see what's going on here.

I think we need to back out the change to fxa-shared and instead do a change just on specific events in the content server (which is what @shane-tomlinson suggested we do initially before I came along and advised otherwise, if memory serves). The problem is that `entrypoint` is a user property and we never pass it to the auth server any more, so it is always going to be set to the service instead.

I can pick this up tomorrow.
